"use strict";

module.exports = {
    plugins: ["stylelint-scss"],
    extends: ["stylelint-config-reflex/base"],
    rules: {
        "at-rule-no-unknown": null,
        "scss/at-each-key-value-single-line": true,
        "scss/at-else-closing-brace-newline-after": "always-last-in-chain",
        "scss/at-else-closing-brace-space-after": "always-intermediate",
        "scss/at-else-empty-line-before": "never",
        "scss/at-else-if-parentheses-space-before": "always",
        "scss/at-extend-no-missing-placeholder": true,
        "scss/at-function-named-arguments": "never",
        "scss/at-function-parentheses-space-before": "never",
        "scss/at-function-pattern": null,
        "scss/at-if-closing-brace-newline-after": "always-last-in-chain",
        "scss/at-if-closing-brace-space-after": "always-intermediate",
        "scss/at-if-no-null": true,
        "scss/at-import-no-partial-leading-underscore": null,
        "scss/at-import-partial-extension": null,
        "scss/at-import-partial-extension-blacklist": null,
        "scss/at-import-partial-extension-whitelist": null,
        "scss/at-mixin-argumentless-call-parentheses": "never",
        "scss/at-mixin-named-arguments": null,
        "scss/at-mixin-parentheses-space-before": "never",
        "scss/at-mixin-pattern": null,
        "scss/at-rule-conditional-no-parentheses": true,
        "scss/at-rule-no-unknown": true,
        "scss/dollar-variable-colon-newline-after": "always-multi-line",
        "scss/dollar-variable-colon-space-after": "always-single-line",
        "scss/dollar-variable-colon-space-before": "never",
        "scss/dollar-variable-empty-line-after": [
            null,
            {
                except: ["before-dollar-variable", "last-nested"],
                ignore: ["inside-single-line-block"],
                disableFix: true,
            },
        ],
        "scss/dollar-variable-empty-line-before": [
            "never",
            {
                ignore: ["after-comment"],
            },
        ],
        "scss/dollar-variable-first-in-block": [
            null,
            {
                ignore: ["comments", "imports"],
                except: ["root", "at-rule", "function", "mixin", "loops"],
            },
        ],
        "scss/dollar-variable-no-missing-interpolation": true,
        "scss/double-slash-comment-whitespace-inside": "always",
        "scss/comment-no-empty": true,
        "scss/comment-no-loud": null,
        "scss/declaration-nested-properties": "never",
        "scss/declaration-nested-properties-no-divided-groups": true,
        "scss/dimension-no-non-numeric-values": true,
        "scss/function-color-relative": true,
        "scss/function-quote-no-quoted-strings-inside": true,
        "scss/function-unquote-no-unquoted-strings-inside": true,
        "scss/map-keys-quotes": "always",
        "scss/media-feature-value-dollar-variable": null,
        "scss/operator-no-newline-after": true,
        "scss/operator-no-newline-before": true,
        "scss/operator-no-unspaced": true,
        "scss/partial-no-import": null,
        "scss/selector-nest-combinators": null,
        "scss/selector-no-redundant-nesting-selector": null,
        "scss/selector-no-union-class-name": null,
        "scss/no-dollar-variables": null,
        "scss/no-duplicate-dollar-variables": null,
        "scss/no-duplicate-mixins": true,
        "scss/no-global-function-names": true,
        "order/order": [
            "dollar-variables",
            "custom-properties",
            "at-variables",
            "declarations",
            "at-rules",
            "rules",
        ],
    },
};
